* mixtures-of-two-gp-experts

This repository contains the code accompanying NeurIPS 2020 submission
/Mixture of Two Gaussian Process Experts using Stochastic Variational Inference/.

This repository contains,
1. saved models that were used to generate the figures in the paper,
2. the data sets,
3. all of the code (including training scripts).

We detail how to,
1. generate the figures in the paper from the saved models,
2. how to train our model on both data sets (and plot).

** Install
This is a Python package that should be installed into a python virtualenv.
Create a new virtualenv and activate it, for example,
#+BEGIN_SRC
mkvirtualenv --python=python3 mogpe-env
workon mogpe-env
#+END_SRC
cd into the root of this package and install it and its dependencies with,
#+BEGIN_SRC
pip install -r requirements.txt
#+END_SRC

** Figures
To reproduce the figures in the paper (using the models saved in [[models/saved_model]]),
- Figure 3a - Run [[src/visualization/plot_artificial_rbf_gating.py]] with,
  #+BEGIN_SRC
    python src/visualization/plot_artificial_rbf_gating.py
  #+END_SRC
- Figure 3b - Run [[src/visualization/plot_artificial_prod_cosine_rbf_gating.py]] with,
  #+BEGIN_SRC
    python src/visualization/plot_artificial_prod_cosine_rbf_gating.py
  #+END_SRC
- Figure 4 - Run [[src/visualization/plot_mcycle.py]] with,
  #+BEGIN_SRC
    python src/visualization/plot_mcycle.py
  #+END_SRC

The json [[configs][config files]] contain the configurations that were used to train the model for each figure.
Our model can be trained from scratch using these config files,
- Artificial data (Figure 3)
  - Figure 3a - Set the =json_file= variable in
    [[src/models/train_and_plot_artificial.py]] to [[configs/figure-3a.json]]
    and then run it.
  - Figure 3b - Set the =json_file= variable in
    [[src/models/train_and_plot_artificial.py]] to [[configs/figure-3b.json]]
    and then run it.
- Motorcycle data (Figure 4) - Run [[src/models/train_and_plot_mcycle.py]]

Figure 1 is not based on our model but instead provides intuition about different
gating network formulations. It was generated with
[[src/visualization/figure_1_comparing_gating_networks.py]].


** Data Sets
The model is tested on two data sets,
1) an artificial data set,
2) the motorcycle data set.

The data sets can be found in the [[data]] directory.
The motorcycle data set was obtained from [[https://vincentarelbundock.github.io/Rdatasets/datasets.html][here]] and is saved at [[data/external/mcycle.csv]].
# The artificial data set was generated with [[src/data/gen_artificial_dataset.py][this script]] and the data set used in the paper is this
# [[data/processed/artificial-data-used-in-paper.npz][numpy file]].
