
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='mogpe',
    version='0.1.0',
    description='GPflow/Tensorflow implementation of mixture of Gaussian process experts - uses sparse GPs and stochastic variational inference',
    python_requires='==3.*,>=3.8.0',
    project_urls={"repository": "https://github.com/aidanscannell/mogpe"},
    author='Aidan Scannell',
    author_email='scannell.aidan@gmail.com',
    license='Apache-2.0',
    packages=['mogpe', 'mogpe.experts', 'mogpe.gating_networks', 'mogpe.gps', 'mogpe.helpers', 'mogpe.mixture_of_experts', 'mogpe.training'],
    package_dir={"": "."},
    package_data={"mogpe": ["*.org"], "mogpe.mixture_of_experts": ["*.py#"]},
    install_requires=['bunch==1.*,>=1.0.1', 'gpflow==2.*,>=2.1.3', 'jupyter==1.*,>=1.0.0', 'matplotlib==3.*,>=3.3.3', 'numpy==1.*,>=1.19.4', 'palettable==3.*,>=3.3.0', 'pandas==1.*,>=1.1.4', 'tensorflow==2.*,>=2.4.0', 'tensorflow-probability==0.*,>=0.12.1'],
    extras_require={"dev": ["black==20.*,>=20.8.0.b1", "isort==5.*,>=5.6.4", "nbsphinx==0.*,>=0.8.0", "nbsphinx-link==1.*,>=1.1.0", "pyflakes==2.*,>=2.2.0", "recommonmark==0.*,>=0.6.0", "sphinx==3.*,>=3.4.0", "sphinx-autodoc-typehints==1.*,>=1.11.1", "sphinx-rtd-theme==0.*,>=0.5.0"]},
)
