* Saved Models
This directory contains the saved models that were used to generate the figures in the paper.

** Artificial Data
Expert one has a cosine kernel and expert two has a squared exponential kernel.
- [[artificial/rbf_gating_kernel]] is our model trained on the artificial data set using a squared exponential
  covariance function for the gating network GP (Figure 3a). This is trained with
  [[../../configs/figure-3a.json]].
- [[artificial/prod_rbf_cosine_kernel]] is our model trained on the artificial data set using the product
  of a squared exponential kernel and a cosine kernel as the covariance function
  for the gating network GP (Figure 3b). This is trained with ([[../../configs/figure-3b.json]])

** Motorcycle Data
- [[mcycle]] is our model trained on the motorcycle data set using
  squared exponential kernels for all GPs (Figure 4). This is trained with ([[../../configs/figure-4-mcycle.json]]).
- =svgp_cycle.npz= is the result of running a sparse variational GP (SVGP) on the motorcycle data set.
  It is used in [[src/visualization]] for generating plots comparing our method to a SVGP.
